//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Games.NBall.Dal.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=180.150.177.96;Initial Catalog=NBall;Persist Security Info=True;User " +
            "ID=nbuser;Password=2df!3T*)d12")]
        public string NBallConnectionString1 {
            get {
                return ((string)(this["NBallConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=180.150.177.96;Initial Catalog=NB_Shadow;Persist Security Info=True;U" +
            "ser ID=nbuser;Password=2df!3T*)d12")]
        public string NB_ShadowConnectionString {
            get {
                return ((string)(this["NB_ShadowConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.28.140.73,20003;Initial Catalog=NB_Config;Persist Security Info=T" +
            "rue;User ID=sa;Password=2df!3T*)d12")]
        public string NB_ConfigConnectionString {
            get {
                return ((string)(this["NB_ConfigConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.28.140.73,20003;Initial Catalog=NBall;Persist Security Info=True;" +
            "User ID=sa;Password=2df!3T*)d12")]
        public string NBallConnectionString {
            get {
                return ((string)(this["NBallConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=180.150.177.96;Initial Catalog=NB_SystemLog;Persist Security Info=Tru" +
            "e;User ID=nbuser;Password=2df!3T*)d12")]
        public string NB_ProcessConnectionString {
            get {
                return ((string)(this["NB_ProcessConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=180.150.177.96;Initial Catalog=NB_SystemLog;Persist Security Info=Tru" +
            "e;User ID=nbuser;Password=2df!3T*)d12")]
        public string NB_SystemlogConnectionString {
            get {
                return ((string)(this["NB_SystemlogConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.28.140.73,20003;Initial Catalog=NBall;Persist Security Info=True;" +
            "User ID=sa;Password=2df!3T*)d12")]
        public string NBallConnectionString2 {
            get {
                return ((string)(this["NBallConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=115.28.140.73,20003;Initial Catalog=NB_Support;Persist Security Info=" +
            "True;User ID=sa;Password=2df!3T*)d12")]
        public string NB_SupportConnectionString {
            get {
                return ((string)(this["NB_SupportConnectionString"]));
            }
        }
    }
}
